### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Amejame** [osurob/Discord-Twitter-Bot#1]
Prints 'bot is ready' but when I post a test tweet nothing happens. Bot is added to servers, has roles etc. everything done well

**Comment by osurob** [comment]
Hello! In Main.py have you updated the Twitter consumer_key, consumer_secret, access_token, access_token_secret to your Twitter values from the Twitter developer portal? Also make sure that your bot has administration privileges that you specify in the Discord developer portal. It is also necessary to change the channel id.

**Comment by Amejame** [comment]
I did everything :( Have you tried to use the monitor on completly new PC or smth?

**Comment by osurob** [comment]
Could you screenshot your code and email it to me? yelasr@oregonstate.edu and I can try to figure out your issue you're having :)

**Comment by osurob** [comment]
I have updated the Github code and added some comments as well.

**Comment by Amejame** [comment]
Okay, I changed the code to the one you updated and now it works correctly as it should. However, could you please give me your discord/twitter or anything to discuss more things and contact faster?

**Comment by osurob** [comment]
Discord is metro#4245 
Glad you got it working!
